In [3]:
import numpy as np

In [5]:
# buat array
a = np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [11]:
np.sum(a)

np.int64(15)

In [13]:
a.sum()

np.int64(15)

In [20]:
a.max()

np.int64(5)

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.random.random(5)

array([0.18531888, 0.55833563, 0.66205792, 0.68925974, 0.2435453 ])